services:
  - type: web
    plan: free
    name: PYRO-RENAME-BOT
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: python -m Krito
    repo: https://github.com/KITITOAK4/Ename.git
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: FORCE_SUB
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: DB_NAME
        sync: false
      - key: DB_URL
        sync: false
      - key: TOKEN_TIMEOUT
        sync: false
      - key: WEBHOOK
        sync: false
      - key: SESSION_STRING
        sync: false
      - key: TEXT
        sync: false
      - key: TEXT1
        sync: false
      - key: TEXT2
        sync: false
      - key: TEXT3
        sync: false
